// "Install Link Meteor and make a first capture": download, unzip, load unpacked, pin,
// capture on the practice page, export from the side panel, shortcuts, help.
export default {
  id: 'link-meteor-install',
  title: 'Install Link Meteor and make your first capture',
  fps: 30,
  fade: 0.4,
  poster: 45,
  scenes: [
    {kind: 'card', variant: 'intro', duration: 3.4, kicker: 'Install and first capture', tagline: 'Set up Link Meteor in <span>desktop Chrome</span>',
      describe: 'The Link Meteor artwork with the title “Set up Link Meteor in desktop Chrome.”'},
    {kind: 'clip', clip: 'tut-install', from: 0.2, to: 'downloaded+1.4', label: 'Install page',
      expect: [{mark: 'downloaded', equals: 'link-meteor-0.2.2.zip'}],
      camera: [{t: 0, zoom: 1, cx: 640, cy: 360}, {t: 'download-1.4', zoom: 1, cx: 640, cy: 360}, {t: 'download-0.3', zoom: 1.35, at: 'download', dx: 120, dy: -60}],
      captions: [{t0: 0.3, t1: 'downloaded+1.4', step: 1, text: 'Download the ZIP from the install page.'}],
      describe: 'The Link Meteor install page scrolls to the download card, and the Download link-meteor-0.2.2.zip button is clicked.'},
    {kind: 'illustration', illustration: 'unzip', duration: 4.8, label: 'Your downloads folder', zip: 'link-meteor-0.2.2.zip', folder: 'link-meteor-0.2.2', entries: ['background.js', 'content/', 'core/', 'icons/', 'manifest.json', 'ui/'],
      captions: [{t0: 0.3, t1: 4.8, step: 2, text: 'Unzip it into a folder you’ll keep. Chrome loads Link Meteor from there.'}],
      describe: 'Illustration: the ZIP file becomes a folder named link-meteor-0.2.2 containing background.js, content, core, icons, manifest.json and ui.'},
    {kind: 'clip', clip: 'tut-ext-before', from: 0.3, to: 'load-unpacked+1.9', label: 'chrome://extensions',
      camera: [{t: 0, zoom: 1, cx: 640, cy: 360}, {t: 'devmode+0.6', zoom: 1, cx: 640, cy: 360}, {t: 'load-unpacked-0.2', zoom: 1.3, cx: 492, cy: 277}],
      captions: [{t0: 0.3, t1: 'devmode+0.7', step: 3, text: 'Open chrome://extensions and turn on Developer mode.'}, {t0: 'devmode+0.8', t1: 'load-unpacked+1.9', step: 3, text: 'Then choose Load unpacked.'}],
      describe: 'The Chrome Extensions page: the Developer mode switch is turned on, revealing Load unpacked, which the pointer moves to.'},
    {kind: 'illustration', illustration: 'pick-folder', duration: 4.6, label: 'Chrome’s file picker', folder: 'link-meteor-0.2.2', entries: ['background.js', 'content', 'core', 'icons', 'manifest.json', 'ui'],
      captions: [{t0: 0.3, t1: 4.6, text: 'Select the unzipped folder, the one that contains manifest.json.'}],
      describe: 'Illustration: in the file picker, the link-meteor-0.2.2 folder is selected; it contains manifest.json.'},
    {kind: 'clip', clip: 'tut-ext-after', from: 0.6, to: 'card+2.4', label: 'chrome://extensions',
      camera: [{t: 0, zoom: 1.9, at: 'card', dx: 60, dy: 30}],
      captions: [{t0: 0.3, t1: 'card+2.4', text: 'Link Meteor 0.2.2 now appears in your extensions.'}],
      describe: 'The Extensions page shows the Link Meteor 0.2.2 card.'},
    {kind: 'illustration', illustration: 'pin', duration: 4.4, label: 'Chrome’s toolbar',
      captions: [{t0: 0.3, t1: 4.4, step: 4, text: 'Pin it from the puzzle-piece menu so the icon stays in view.'}],
      describe: 'Illustration: the Extensions puzzle-piece menu is opened and Link Meteor is pinned, so its icon appears in the toolbar.'},
    {kind: 'clip', clip: 'tut-capture', from: 'shortcut-1.0', to: 'status+2.8', label: 'Practice page · search results',
      expect: [{mark: 'count', equals: '9 links selected'}, {mark: 'copy-status', startsWith: 'Copied anchor text and URL'}, {mark: 'status', startsWith: 'Saved 9 links'}],
      keys: {t0: 'shortcut-0.1', t1: 'armed+1.3', caps: ['⌥', '⇧', 'L'], note: '<b>Option Shift L</b>Alt Shift L on Windows and Linux'},
      camera: [{t: 0, zoom: 1, cx: 640, cy: 360}, {t: 'drag-start', zoom: 1, cx: 640, cy: 360}, {t: 'drag-start+0.8', zoom: 1.1, cx: 600, cy: 340}, {t: 'released', zoom: 1.1, cx: 600, cy: 340}, {t: 'released+0.7', zoom: 1.5, cx: 1060, cy: 540}],
      captions: [
        {t0: 'shortcut-0.9', t1: 'drag-start-0.1', step: 5, text: 'On the practice page, press the shortcut…'},
        {t0: 'drag-start', t1: 'released', step: 5, text: '…and drag across one section.'},
        {t0: 'released+0.1', t1: 'copy-0.1', text: 'Compare the count with the section’s answer key: 9 links.'},
        {t0: 'copy', t1: 'added-0.1', text: 'Copy text + URL puts two columns on your clipboard.'},
        {t0: 'added', t1: 'status+2.8', text: 'Or add them to a collection to review later.'}],
      describe: 'On the practice page, the search results section is selected. The card reads “9 links selected.” Copy text + URL reports “Copied anchor text and URL as two spreadsheet columns,” then Add to collection saves them.'},
    {kind: 'clip', clip: 'tut-panel', from: 0.3, to: 'downloaded+2.8', label: 'Side panel', layout: 'panel', still: 'tut-capture-still.jpg', stillLabel: 'Practice page',
      expect: [{mark: 'downloaded', equals: 'Urban-heat-islands-sources.csv'}],
      camera: [{t: 0, zoom: 1, cx: 200, cy: 360}],
      captions: [
        {t0: 0.3, t1: 'export-view-0.2', step: 6, text: 'Click the Link Meteor icon to open its side panel beside the page.'},
        {t0: 'export-view-0.1', t1: 'download-0.2', step: 6, text: 'Export shows exactly which links it will use.'},
        {t0: 'download-0.1', t1: 'downloaded+2.8', step: 6, text: 'Pick a format and download. Here, CSV.'}],
      describe: 'The Link Meteor side panel lists the captured links beside the practice page. Export opens the export view, where CSV is chosen and downloaded.'},
    {kind: 'clip', clip: 'tut-shortcuts', from: 0.5, to: 'shortcut-field+2.3', label: 'chrome://extensions/shortcuts',
      camera: [{t: 0, zoom: 1.9, at: 'shortcut-field', dx: -40, dy: -10}],
      captions: [{t0: 0.3, t1: 'shortcut-field+2.3', text: 'If the shortcut doesn’t work, change it at chrome://extensions/shortcuts.'}],
      describe: 'The Chrome keyboard shortcuts page shows Link Meteor’s “Select a region of links” shortcut.'},
    {kind: 'clip', clip: 'tut-about', from: 0.4, to: 'issues+3.2', label: 'Side panel', layout: 'panel', still: 'tut-capture-still.jpg', stillLabel: 'Practice page',
      camera: [{t: 0, zoom: 1, cx: 200, cy: 360}],
      captions: [{t0: 0.3, t1: 'issues-0.3', text: 'Help, bug reports and suggestions are under About and help.'}, {t0: 'issues-0.2', t1: 'issues+3.2', text: 'Reports are public, so leave out private URLs and data.'}],
      describe: 'In the side panel, the help button opens About and help, with the version, “made by Ryan Kamp,” and links to the guide, bug reports and suggestions, the website, source code and optional sponsorship.'},
    {kind: 'card', variant: 'outro', duration: 5.2, title: 'You’re set. <span>Go collect your sources.</span>', promises: ['Free forever', 'No account', 'No tracking', 'Stays in your browser'], url: 'ryanjosephkamp.github.io/link-meteor', by: 'Made by Ryan Kamp',
      describe: 'Closing card with the promises, the website address and “Made by Ryan Kamp.”'},
  ],
};
